FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
WORKDIR /ArabicLearning

COPY ./ArabicLearning/*.csproj ./
RUN dotnet restore

COPY ./ArabicLearning ./
RUN dotnet publish -c Release -o out

#building into image the wait-for-it script
# COPY wait-for-it.sh /wait-for-it.sh
# RUN chmod +x /wait-for-it.sh

COPY ./entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh

RUN dotnet tool install -g dotnet-ef 
RUN dotnet dev-certs https
ENV PATH $PATH:/root/.dotnet/tools

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /ArabicLearning
COPY --from=build-env /ArabicLearning/out .

ENTRYPOINT ["dotnet", "ArabicLearning.dll"]